### ISSUE TITLE
m4_perspective uses row major but should use column major

### ISSUE THREAD

**Issue by zbynekwinkler** [arkanis/single-header-file-c-libs#1]
I believe that according to the description in the file the function `m4_perspective` wrongly sets the matrix as if it is row major. See 
https://github.com/arkanis/single-header-file-c-libs/blob/07a69d432f39984d1bd7372cbab8c27dcf6b2f4c/math_3d.h#L438

**Comment by arkanis** [comment]
Hi zwn,

thanks for looking at the code and the feedback! The key here is the mat4() function. It takes the matrix elements in "row major order" (or rather by name) so you can write the matrix in the same way as on paper. That is visually similar to the mathematical notation. It's described in the matrix documentation (see [line 121](https://github.com/arkanis/single-header-file-c-libs/blob/07a69d432f39984d1bd7372cbab8c27dcf6b2f4c/math_3d.h#L121)).

The mat4() function uses named arguments and sets all matrix members by name instead of transposing an input array. That way it's easier to be absolutely sure that every matrix element is where it should be.

Hope that helps. Fell free to ask anything about the code. I'm happy it actually helps someone. :)

**Comment by zbynekwinkler** [comment]
Oh, that explains it :+1: I like how readable the code is but I must have missed it.
