### ISSUE TITLE
Using *_t for type names should be avoided.

### ISSUE THREAD

**Issue by ghost** [arkanis/single-header-file-c-libs#4]
Just a minor gripe: the GCC manual recommends avoiding the use of _t for type names, since it is reserved by POSIX for type names.

"Names that end with ‘_t’ are reserved for additional type names."
https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

Further discussion on the topic here:
https://stackoverflow.com/questions/231760/what-does-a-type-followed-by-t-underscore-t-represent

Anyway just a minor bit of pedantry really, I've seen quite a few libraries abuse the _t, but since you specifically mention supporting GCC in another comment I thought I would raise the issue. Cheers, and thanks for the great library!

**Comment by arkanis** [comment]
Thanks for using the library and posting feedback Segmented. :)

I read about that somewhere in the past but kind of ignored it. This wasn't a real decision just kind of "current style" I picked up from other C libraries (e.g. x264). Personally I use the _t suffix for value types and the _p suffix for pointer types so it just seemed natural to use _t for the vector and matrix types.

In the special context of the library it was a nice way to avoid naming conflicts between constructor functions like vec3() and mat4() and type names (vec3_t and mat4_t). The hope was that this is the way of least surprise for users (I hope it actually is).

Since POSIX / SUS is unlikely to define matrix and vector types for their operating system interface I'm not particularly afraid of naming collisions. But I'll keep it in mind for other libraries. So thanks for the heads up.

If you have any good ideas for alternative type names feel free to reopen the issue and let me know. :)

**Comment by ghost** [comment]
Well, as far as alternatives, what I use for non-opaque types is avoid the typedef altogether, so something like: struct mat4 mat4() would be possible with no conflict.

**Comment by arkanis** [comment]
Hm, I've read about that in the Linux kernel coding guidelines and kind of liked the idea. No surprises when writing types like that.

But the math library is meant to be used with OpenGL, and that means GLSL isn't far away. That somewhat changes the expectation of users and in GLSL the types are simply vec3 and mat4. That's actually the reason I named the constructor functions like that. They're typed more often than type names, so they got the shorter name.

I'll give the struct mat4 and struct vec3 a try in my next small dummy project to get a feel for it. Maybe the library itself could use struct vec3 and struct mat4 but provide vec3_t and mat4_t typedefs that can be disabled with a define (like MATH_3D_NO_TYPEDEFS). Do you think that is useful or would just be fussing about details and confusing users?

**Comment by ghost** [comment]
Well the name incompatibility only exists on POSIX systems, so you could I suppose detect posix and conditionally create the typedefs, something like #if defined(\_\_unix__) || defined(_POSIX_VERSION). However, personally I would just choose one or the other so people don't get confused when trying to follow tutorials/examples.

I can see the point about GLSL, however vec3_t v = vec3() and struct vec3 v = vec3() are both different from the GLSL's vec3 v = vec3() anyway. I don't think anyone would be confused by either option, so I would probably let C look like C in this case, but ultimately that is up to you.

**Comment by arkanis** [comment]
You're right. I'll give struct vec3 a try in my next project to get a feeling for it.

I've just published a library for a C99 hashmap and made the typedefs optional there. The library itself and the docs also use the structs directly. So the typedefs are just a nice extra feature that can be disabled. If you want you can take a look if that's something that makes sense.

https://github.com/arkanis/single-header-file-c-libs/blob/master/slim_hash.h

To me it looks like there is a slow kind of coding style migration in progress. Back from typedefed structs to manual struct syntax. But I'm not sure if this is a large-scale change of just a thing in some small C subcommunities.
